// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AspireDemo.ApiService.Data.Models;

public partial class VPM
{
    public int Id { get; set; }

    public Guid Rid { get; set; }

    public string Name { get; set; }

    public double Grade { get; set; }

    public double WallThickness { get; set; }

    public double? Diameter { get; set; }

    public int EPSG { get; set; }

    public string Color { get; set; }

    public virtual ICollection<VPMEvent> VPMEvent { get; set; } = new List<VPMEvent>();

    public virtual ICollection<VPMGps> VPMGps { get; set; } = new List<VPMGps>();
}