// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AspireDemo.ApiService.Data.Models;

public partial class VPMEventType
{
    public int Id { get; set; }

    public string Description { get; set; }

    public virtual ICollection<VPMEvent> VPMEvent { get; set; } = new List<VPMEvent>();
}