// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AspireDemo.ApiService.Data.Models;

public partial class VPMEvent
{
    public int Id { get; set; }

    public int VPMId { get; set; }

    public int VPMEventTypeId { get; set; }

    public double DFS { get; set; }

    public double Clock { get; set; }

    public double Length { get; set; }

    public double Width { get; set; }

    public virtual VPM VPM { get; set; }

    public virtual VPMEventType VPMEventType { get; set; }
}