// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AspireDemo.ApiService.Data.Models;

public partial class VPMGps
{
    public int Id { get; set; }

    public int VPMId { get; set; }

    public double Longitude { get; set; }

    public double Latitude { get; set; }

    public double? Elevation { get; set; }

    public double DFS { get; set; }

    public int VPMGpsTypeId { get; set; }

    public string Description { get; set; }

    public virtual VPM VPM { get; set; }

    public virtual VPMGpsType VPMGpsType { get; set; }
}